#pragma once

// place overrides here
#undef TAPPING_TERM
#undef TAPPING_TOGGLE
#undef USB_POLLING_INTERVAL_MS
#undef HOLD_ON_OTHER_KEY_PRESS_PER_KEY
#undef LED_CAPS_LOCK_PIN
#undef LED_PIN_ON_STATE

#define TAPPING_TOGGLE 2
#define TAPPING_TERM 175
#define USB_POLLING_INTERVAL_MS 1
#define HOLD_ON_OTHER_KEY_PRESS_PER_KEY
#define LED_CAPS_LOCK_PIN B7
#define LED_PIN_ON_STATE 1