BOOTMAGIC_ENABLE = yes
TAP_DANCE_ENABLE = yes
EXTRAKEY_ENABLE = no
VIA_ENABLE = yes
MOUSEKEY_ENABLE = no
CONSOLE_ENABLE = no        # Console for debug
COMMAND_ENABLE = no        # Commands for debug and configuration
LTO_ENABLE = yes
RGBLIGHT_ENABLE = no